//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UATachi
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Category
    {
        public Category()
        {
            this.Products = new ObservableCollection<Product>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual ObservableCollection<Product> Products { get; set; }
    }
}
